output_dir: "output"

cluster:
  partition: "nodes*"
  
resources:
  convert_contig:
    mem: "6G"
    time: "07:30:00"
    threads: 10
  subset_BCF:
    mem: "3G"
    time: "03:30:00"  
    threads: 10
  convert_parquet:
    mem: "8G"
    time: "05:30:00"
  combine_all_parquets:
    mem: "16G"
    time: "02:00:00"
